"""
AI-Times Agent.

Fetches the latest AI-related videos from YouTube,
uses the local LLM to generate summaries, and sends
a daily HTML email digest.

Schedule: Daily at a configurable time (default 8:00 AM)
Trigger: Manual from dashboard
"""

from agents.base_agent import BaseAgent
from orchestrator.scheduler import llm_scheduler, RequestPriority
from services.youtube_service import youtube_service
from services.email_service import email_service
from jinja2 import Template


AI_TIMES_EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: Arial, sans-serif; background: #f5f5f5; padding: 20px; }
  .container { max-width: 700px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; }
  .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; }
  .header h1 { margin: 0; font-size: 28px; }
  .header p { margin: 5px 0 0; opacity: 0.9; }
  .summary { padding: 20px; background: #f8f9ff; border-bottom: 1px solid #e0e0e0; }
  .summary h2 { color: #333; margin-top: 0; }
  .summary p { color: #555; line-height: 1.6; }
  .video { padding: 20px; border-bottom: 1px solid #eee; }
  .video:last-child { border-bottom: none; }
  .video h3 { margin: 0 0 8px; }
  .video h3 a { color: #667eea; text-decoration: none; }
  .video h3 a:hover { text-decoration: underline; }
  .meta { color: #888; font-size: 13px; margin-bottom: 8px; }
  .footer { padding: 20px; text-align: center; color: #999; font-size: 12px; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>AI Times Daily Digest</h1>
    <p>{{ date }} &bull; {{ video_count }} videos curated</p>
  </div>
  <div class="summary">
    <h2>Today's AI Highlights</h2>
    <p>{{ llm_summary }}</p>
  </div>
  {% for video in videos %}
  <div class="video">
    <h3><a href="{{ video.url }}">{{ video.title }}</a></h3>
    <div class="meta">{{ video.channel }} &bull; {{ video.views }} &bull; {{ video.published }} &bull; {{ video.duration }}</div>
  </div>
  {% endfor %}
  <div class="footer">
    Generated by AI-Times Agent &bull; Multi-Agent Platform
  </div>
</div>
</body>
</html>
"""


class AITimesAgent(BaseAgent):
    """
    Fetches AI news videos from YouTube, summarizes them with
    the local LLM, and sends a daily email digest.
    """

    def __init__(self):
        super().__init__(
            agent_id="ai_times",
            name="AI-Times",
            description="Fetches latest AI YouTube videos and sends daily HTML email digest",
        )

    async def execute(self) -> int:
        """
        1. Scrape YouTube for latest AI videos
        2. Use LLM to summarize the collection
        3. Send HTML email digest
        """
        await self.log("INFO", "Searching YouTube for AI news videos...")

        # Step 1: Fetch videos
        videos = youtube_service.search_videos(
            query="AI news artificial intelligence",
            limit=10,
            sort_by="upload_date",
        )

        if not videos:
            await self.log("WARNING", "No videos found from YouTube search")
            return 0

        await self.log("INFO", f"Found {len(videos)} videos")

        # Step 2: Generate LLM summary of all video titles
        video_titles = "\n".join(
            f"- {v['title']} (by {v['channel']}, {v['published']})"
            for v in videos
        )

        prompt = (
            f"Here are the latest AI-related YouTube videos:\n\n"
            f"{video_titles}\n\n"
            f"Write a brief 3-4 sentence summary highlighting the key AI trends "
            f"and topics covered in these videos. Be concise and informative."
        )

        system_prompt = (
            "You are a tech journalist summarizing the latest AI news. "
            "Be factual, concise, and highlight the most important trends."
        )

        try:
            llm_result = await llm_scheduler.submit(
                agent_id=self.agent_id,
                task_description="Summarize AI video collection",
                prompt=prompt,
                system_prompt=system_prompt,
                priority=RequestPriority.NORMAL,
                max_tokens=300,
            )
            summary = llm_result["response"]
        except Exception as e:
            await self.log("WARNING", f"LLM summary failed: {e}, using fallback")
            summary = (
                f"Today's digest features {len(videos)} AI-related videos "
                f"covering the latest developments in artificial intelligence."
            )

        # Step 3: Render and send email
        from datetime import datetime
        template = Template(AI_TIMES_EMAIL_TEMPLATE)
        html = template.render(
            date=datetime.now().strftime("%B %d, %Y"),
            video_count=len(videos),
            llm_summary=summary,
            videos=videos,
        )

        sent = await email_service.send_html_email(
            subject=f"AI Times Daily Digest - {datetime.now().strftime('%b %d')}",
            html_body=html,
        )

        if sent:
            await self.log("INFO", "Email digest sent successfully")
        else:
            await self.log("WARNING", "Email send failed or not configured")

        return len(videos)
