"""
News Analyst Agent.

Fetches news articles from RSS feeds, uses the local LLM to analyze
sentiment and classify importance, and sends a daily digest email.

Schedule: Daily at a configurable time (default 7:00 AM)
Trigger: Manual from dashboard
"""

import feedparser
from datetime import datetime

from agents.base_agent import BaseAgent
from orchestrator.scheduler import llm_scheduler, RequestPriority
from services.email_service import email_service
from database.db import get_db
from jinja2 import Template


NEWS_EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: Arial, sans-serif; background: #f5f5f5; padding: 20px; }
  .container { max-width: 700px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; }
  .header { background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); color: white; padding: 30px; text-align: center; }
  .header h1 { margin: 0; font-size: 28px; }
  .header p { margin: 5px 0 0; opacity: 0.9; }
  .overview { padding: 20px; background: #fff5f7; border-bottom: 1px solid #e0e0e0; }
  .overview h2 { color: #333; margin-top: 0; }
  .overview p { color: #555; line-height: 1.6; }
  .article { padding: 15px 20px; border-bottom: 1px solid #eee; }
  .article:last-child { border-bottom: none; }
  .article h3 { margin: 0 0 6px; font-size: 16px; }
  .article h3 a { color: #f5576c; text-decoration: none; }
  .article h3 a:hover { text-decoration: underline; }
  .meta { color: #888; font-size: 12px; margin-bottom: 6px; }
  .sentiment { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: bold; }
  .positive { background: #d4edda; color: #155724; }
  .negative { background: #f8d7da; color: #721c24; }
  .neutral { background: #e2e3e5; color: #383d41; }
  .summary-text { color: #555; font-size: 13px; line-height: 1.5; }
  .footer { padding: 20px; text-align: center; color: #999; font-size: 12px; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>News Analyst Daily Digest</h1>
    <p>{{ date }} &bull; {{ article_count }} articles analyzed</p>
  </div>
  <div class="overview">
    <h2>Today's Overview</h2>
    <p>{{ llm_overview }}</p>
  </div>
  {% for article in articles %}
  <div class="article">
    <h3><a href="{{ article.link }}">{{ article.title }}</a></h3>
    <div class="meta">
      {{ article.source }} &bull; {{ article.published }}
      &bull; <span class="sentiment {{ article.sentiment|lower }}">{{ article.sentiment }}</span>
      &bull; Importance: {{ article.importance }}/5
    </div>
    <div class="summary-text">{{ article.llm_summary }}</div>
  </div>
  {% endfor %}
  <div class="footer">
    Generated by News Analyst Agent &bull; Multi-Agent Platform
  </div>
</div>
</body>
</html>
"""


class NewsAnalystAgent(BaseAgent):
    """
    Fetches news from RSS feeds, analyzes sentiment and importance
    with LLM, and sends a daily digest email.
    """

    def __init__(self):
        super().__init__(
            agent_id="news_analyst",
            name="News Analyst",
            description="Fetches news via RSS feeds; LLM sentiment analysis; daily digest email",
        )

    async def execute(self) -> int:
        """
        1. Load RSS feed sources from database
        2. Fetch articles from all feeds
        3. Use LLM to analyze each article (sentiment + importance + summary)
        4. Generate overview and send email digest
        """
        await self.log("INFO", "Loading RSS feed sources...")

        # Step 1: Get feed URLs from DB
        sources = await self._get_feed_sources()
        if not sources:
            await self.log("WARNING", "No RSS feed sources configured")
            return 0

        await self.log("INFO", f"Fetching from {len(sources)} RSS sources")

        # Step 2: Fetch articles
        articles = await self._fetch_all_feeds(sources)
        if not articles:
            await self.log("WARNING", "No articles fetched from RSS feeds")
            return 0

        # Limit to top 15 most recent
        articles = articles[:15]
        await self.log("INFO", f"Analyzing {len(articles)} articles")

        # Step 3: Analyze each article with LLM
        analyzed = []
        for article in articles:
            try:
                analysis = await self._analyze_article(article)
                article.update(analysis)
                analyzed.append(article)
            except Exception as e:
                await self.log(
                    "WARNING",
                    f"Failed to analyze: {article['title'][:50]}: {e}"
                )
                # Add with defaults
                article.update({
                    "sentiment": "NEUTRAL",
                    "importance": 3,
                    "llm_summary": article.get("summary", "")[:200],
                })
                analyzed.append(article)

        # Step 4: Generate overview and send email
        overview = await self._generate_overview(analyzed)

        template = Template(NEWS_EMAIL_TEMPLATE)
        html = template.render(
            date=datetime.now().strftime("%B %d, %Y"),
            article_count=len(analyzed),
            llm_overview=overview,
            articles=analyzed,
        )

        sent = await email_service.send_html_email(
            subject=f"News Analyst Digest - {datetime.now().strftime('%b %d')}",
            html_body=html,
        )

        if sent:
            await self.log("INFO", "News digest email sent successfully")
        else:
            await self.log("WARNING", "Email send failed or not configured")

        return len(analyzed)

    async def _get_feed_sources(self) -> list[dict]:
        """Get enabled RSS feed sources from the database."""
        db = await get_db()
        cursor = await db.execute(
            "SELECT name, url, category FROM news_sources WHERE enabled = 1"
        )
        rows = await cursor.fetchall()
        return [dict(row) for row in rows]

    async def _fetch_all_feeds(self, sources: list[dict]) -> list[dict]:
        """Fetch and parse articles from all RSS feeds."""
        import asyncio

        def _fetch():
            all_articles = []
            for source in sources:
                try:
                    feed = feedparser.parse(source["url"])
                    for entry in feed.entries[:5]:  # Max 5 per source
                        published = entry.get("published", "")
                        summary = entry.get("summary", entry.get("description", ""))
                        # Strip HTML tags from summary
                        import re
                        clean_summary = re.sub(r"<[^>]+>", "", summary)

                        all_articles.append({
                            "title": entry.get("title", "Untitled"),
                            "link": entry.get("link", ""),
                            "summary": clean_summary[:500],
                            "published": published[:30] if published else "Unknown",
                            "source": source["name"],
                            "category": source["category"],
                        })
                except Exception as e:
                    print(f"[NEWS] Failed to parse {source['name']}: {e}")

            # Sort by most recent (rough sort by source order)
            return all_articles

        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, _fetch)

    async def _analyze_article(self, article: dict) -> dict:
        """Use LLM to analyze an article's sentiment and importance."""
        prompt = (
            f"Analyze this news article:\n\n"
            f"Title: {article['title']}\n"
            f"Source: {article['source']}\n"
            f"Summary: {article['summary'][:300]}\n\n"
            f"Provide:\n"
            f"1. SENTIMENT: POSITIVE, NEGATIVE, or NEUTRAL\n"
            f"2. IMPORTANCE: 1-5 (1=trivial, 5=major breaking news)\n"
            f"3. SUMMARY: A one-sentence summary (max 30 words)\n\n"
            f"Format your response exactly as:\n"
            f"SENTIMENT: [value]\n"
            f"IMPORTANCE: [value]\n"
            f"SUMMARY: [value]"
        )

        system_prompt = (
            "You are a news analyst. Analyze articles for sentiment and importance. "
            "Always respond in the exact format requested. Be concise."
        )

        result = await llm_scheduler.submit(
            agent_id=self.agent_id,
            task_description=f"Analyze: {article['title'][:40]}",
            prompt=prompt,
            system_prompt=system_prompt,
            priority=RequestPriority.NORMAL,
            temperature=0.3,
            max_tokens=150,
        )

        response = result["response"]
        return self._parse_analysis(response, article)

    def _parse_analysis(self, response: str, article: dict) -> dict:
        """Parse the LLM analysis response."""
        sentiment = "NEUTRAL"
        importance = 3
        summary = article.get("summary", "")[:150]

        lines = response.strip().split("\n")
        for line in lines:
            line = line.strip()
            if line.upper().startswith("SENTIMENT:"):
                val = line.split(":", 1)[1].strip().upper()
                if val in ("POSITIVE", "NEGATIVE", "NEUTRAL"):
                    sentiment = val
            elif line.upper().startswith("IMPORTANCE:"):
                try:
                    val = int(line.split(":", 1)[1].strip().split()[0])
                    importance = max(1, min(5, val))
                except (ValueError, IndexError):
                    pass
            elif line.upper().startswith("SUMMARY:"):
                summary = line.split(":", 1)[1].strip()

        return {
            "sentiment": sentiment,
            "importance": importance,
            "llm_summary": summary,
        }

    async def _generate_overview(self, articles: list[dict]) -> str:
        """Generate an LLM overview of all analyzed articles."""
        headlines = "\n".join(
            f"- [{a['sentiment']}] {a['title']} ({a['source']})"
            for a in articles[:10]
        )

        positive = sum(1 for a in articles if a["sentiment"] == "POSITIVE")
        negative = sum(1 for a in articles if a["sentiment"] == "NEGATIVE")
        neutral = len(articles) - positive - negative

        prompt = (
            f"Today's news summary ({len(articles)} articles analyzed):\n"
            f"Sentiment breakdown: {positive} positive, {negative} negative, "
            f"{neutral} neutral\n\n"
            f"Headlines:\n{headlines}\n\n"
            f"Write a 3-4 sentence overview of today's news, highlighting "
            f"the most important stories and overall sentiment trends."
        )

        system_prompt = (
            "You are a news editor writing a daily overview. "
            "Be factual, concise, and highlight the most significant stories."
        )

        try:
            result = await llm_scheduler.submit(
                agent_id=self.agent_id,
                task_description="Generate daily news overview",
                prompt=prompt,
                system_prompt=system_prompt,
                priority=RequestPriority.NORMAL,
                max_tokens=300,
            )
            return result["response"]
        except Exception as e:
            await self.log("WARNING", f"LLM overview failed: {e}")
            return (
                f"Today's digest covers {len(articles)} articles across "
                f"multiple sources. Sentiment is mixed with {positive} positive, "
                f"{negative} negative, and {neutral} neutral articles."
            )
