"""
Wallstreet Wolf Agent.

Tracks 25 stocks via Yahoo Finance, uses the local LLM to generate
market commentary, and sends a daily email report.

Schedule: Daily at market close (default 4:30 PM ET)
Trigger: Manual from dashboard
"""

import yfinance as yf
from datetime import datetime

from agents.base_agent import BaseAgent
from orchestrator.scheduler import llm_scheduler, RequestPriority
from services.email_service import email_service
from database.db import get_db
from jinja2 import Template


WALLSTREET_EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: Arial, sans-serif; background: #f5f5f5; padding: 20px; }
  .container { max-width: 700px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; }
  .header { background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%); color: white; padding: 30px; text-align: center; }
  .header h1 { margin: 0; font-size: 28px; }
  .header p { margin: 5px 0 0; opacity: 0.9; }
  .commentary { padding: 20px; background: #f0faf5; border-bottom: 1px solid #e0e0e0; }
  .commentary h2 { color: #333; margin-top: 0; }
  .commentary p { color: #555; line-height: 1.6; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #f8f9fa; padding: 12px 15px; text-align: left; font-size: 13px; color: #666; border-bottom: 2px solid #dee2e6; }
  td { padding: 10px 15px; border-bottom: 1px solid #eee; font-size: 14px; }
  .ticker { font-weight: bold; color: #333; }
  .green { color: #28a745; }
  .red { color: #dc3545; }
  .summary-row { background: #f8f9fa; }
  .footer { padding: 20px; text-align: center; color: #999; font-size: 12px; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>Wallstreet Wolf Daily Report</h1>
    <p>{{ date }} &bull; {{ stock_count }} stocks tracked</p>
  </div>
  <div class="commentary">
    <h2>Market Commentary</h2>
    <p>{{ llm_commentary }}</p>
  </div>
  <table>
    <tr>
      <th>Ticker</th>
      <th>Price</th>
      <th>Change</th>
      <th>Change %</th>
      <th>Volume</th>
    </tr>
    {% for stock in stocks %}
    <tr>
      <td class="ticker">{{ stock.ticker }}</td>
      <td>${{ "%.2f"|format(stock.price) }}</td>
      <td class="{{ 'green' if stock.change >= 0 else 'red' }}">
        {{ "+" if stock.change >= 0 }}{{ "%.2f"|format(stock.change) }}
      </td>
      <td class="{{ 'green' if stock.change_pct >= 0 else 'red' }}">
        {{ "+" if stock.change_pct >= 0 }}{{ "%.2f"|format(stock.change_pct) }}%
      </td>
      <td>{{ stock.volume }}</td>
    </tr>
    {% endfor %}
    <tr class="summary-row">
      <td colspan="2"><strong>Gainers: {{ gainers }}</strong></td>
      <td colspan="3"><strong>Losers: {{ losers }}</strong></td>
    </tr>
  </table>
  <div class="footer">
    Generated by Wallstreet Wolf Agent &bull; Multi-Agent Platform
  </div>
</div>
</body>
</html>
"""


class WallstreetWolfAgent(BaseAgent):
    """
    Tracks stocks via Yahoo Finance, generates LLM commentary,
    and sends daily email reports.
    """

    def __init__(self):
        super().__init__(
            agent_id="wallstreet_wolf",
            name="Wallstreet Wolf",
            description="Tracks 20+ stocks via Yahoo Finance; LLM commentary; daily email",
        )

    async def execute(self) -> int:
        """
        1. Load stock tickers from database
        2. Fetch current prices from Yahoo Finance
        3. Generate LLM market commentary
        4. Send email report
        """
        await self.log("INFO", "Loading stock watchlist...")

        # Step 1: Get tickers from DB
        tickers = await self._get_watchlist()
        if not tickers:
            await self.log("WARNING", "No stocks in watchlist")
            return 0

        await self.log("INFO", f"Tracking {len(tickers)} stocks")

        # Step 2: Fetch stock data
        await self.log("INFO", "Fetching stock data from Yahoo Finance...")
        stocks = await self._fetch_stock_data(tickers)

        if not stocks:
            await self.log("ERROR", "Failed to fetch any stock data")
            return 0

        await self.log("INFO", f"Got data for {len(stocks)} stocks")

        # Step 3: Generate LLM commentary
        commentary = await self._generate_commentary(stocks)

        # Step 4: Send email
        gainers = sum(1 for s in stocks if s["change"] >= 0)
        losers = len(stocks) - gainers

        template = Template(WALLSTREET_EMAIL_TEMPLATE)
        html = template.render(
            date=datetime.now().strftime("%B %d, %Y"),
            stock_count=len(stocks),
            llm_commentary=commentary,
            stocks=stocks,
            gainers=gainers,
            losers=losers,
        )

        sent = await email_service.send_html_email(
            subject=f"Wallstreet Wolf Report - {datetime.now().strftime('%b %d')}",
            html_body=html,
        )

        if sent:
            await self.log("INFO", "Stock report email sent successfully")
        else:
            await self.log("WARNING", "Email send failed or not configured")

        return len(stocks)

    async def _get_watchlist(self) -> list[str]:
        """Get enabled stock tickers from the database."""
        db = await get_db()
        cursor = await db.execute(
            "SELECT ticker FROM stocks WHERE enabled = 1 ORDER BY ticker"
        )
        rows = await cursor.fetchall()
        return [row["ticker"] for row in rows]

    async def _fetch_stock_data(self, tickers: list[str]) -> list[dict]:
        """Fetch current stock data from Yahoo Finance."""
        import asyncio
        import ssl
        import os

        def _fetch():
            # Disable SSL verification for corporate proxies (Zscaler etc.)
            os.environ["PYTHONHTTPSVERIFY"] = "0"
            ssl._create_default_https_context = ssl._create_unverified_context

            # yfinance uses curl_cffi which needs explicit verify=False
            from curl_cffi.requests import Session
            session = Session(verify=False)

            results = []
            for ticker in tickers:
                try:
                    stock = yf.Ticker(ticker, session=session)
                    info = stock.fast_info

                    price = getattr(info, "last_price", 0) or 0
                    prev_close = getattr(info, "previous_close", 0) or 0
                    change = price - prev_close if prev_close else 0
                    change_pct = (change / prev_close * 100) if prev_close else 0

                    market_cap = getattr(info, "market_cap", 0) or 0
                    volume = getattr(info, "last_volume", 0) or 0

                    # Format volume
                    if volume >= 1_000_000:
                        vol_str = f"{volume / 1_000_000:.1f}M"
                    elif volume >= 1_000:
                        vol_str = f"{volume / 1_000:.1f}K"
                    else:
                        vol_str = str(volume)

                    results.append({
                        "ticker": ticker,
                        "price": round(price, 2),
                        "prev_close": round(prev_close, 2),
                        "change": round(change, 2),
                        "change_pct": round(change_pct, 2),
                        "volume": vol_str,
                        "market_cap": market_cap,
                    })
                except Exception as e:
                    print(f"[WALLSTREET] Failed to fetch {ticker}: {e}")

            return results

        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, _fetch)

    async def _generate_commentary(self, stocks: list[dict]) -> str:
        """Use LLM to generate market commentary."""
        # Build stock summary for LLM
        top_gainers = sorted(stocks, key=lambda s: s["change_pct"], reverse=True)[:5]
        top_losers = sorted(stocks, key=lambda s: s["change_pct"])[:5]

        summary_lines = []
        summary_lines.append("TOP GAINERS:")
        for s in top_gainers:
            summary_lines.append(
                f"  {s['ticker']}: ${s['price']:.2f} ({s['change_pct']:+.2f}%)"
            )
        summary_lines.append("\nTOP LOSERS:")
        for s in top_losers:
            summary_lines.append(
                f"  {s['ticker']}: ${s['price']:.2f} ({s['change_pct']:+.2f}%)"
            )

        prompt = (
            f"Here is today's stock market summary for a watchlist of "
            f"{len(stocks)} tech/growth stocks:\n\n"
            f"{chr(10).join(summary_lines)}\n\n"
            f"Write a 3-4 sentence market commentary highlighting key movers, "
            f"possible reasons for the moves, and overall market sentiment. "
            f"Be analytical and concise."
        )

        system_prompt = (
            "You are a financial analyst providing daily market commentary. "
            "Be factual, analytical, and concise. Do not give investment advice."
        )

        try:
            result = await llm_scheduler.submit(
                agent_id=self.agent_id,
                task_description="Generate daily market commentary",
                prompt=prompt,
                system_prompt=system_prompt,
                priority=RequestPriority.NORMAL,
                max_tokens=400,
            )
            return result["response"]
        except Exception as e:
            await self.log("WARNING", f"LLM commentary failed: {e}")
            gainers = sum(1 for s in stocks if s["change"] >= 0)
            return (
                f"Today's market showed mixed results across {len(stocks)} tracked stocks, "
                f"with {gainers} gainers and {len(stocks) - gainers} losers."
            )
